
'use server';
/**
 * @fileOverview An AI flow for providing handicap suggestions for snooker players.
 *
 * This file defines a Genkit flow that takes player statistics as input and
 * returns an AI-generated handicap suggestion and the reasoning behind it.
 *
 * - handicapAdvisorFlow - The main flow function.
 * - HandicapAdvisorInput - The Zod schema for the flow's input.
 * - HandicapAdvisorOutput - The Zod schema for the flow's output.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';
import type {Player} from '@/app/players/page';

/**
 * Zod schema for the handicap advisor flow input.
 * Expects a stringified JSON object of player data.
 */
export const HandicapAdvisorInputSchema = z.object({
  playerData: z.string().describe('A JSON string representing the player\'s data.'),
});
export type HandicapAdvisorInput = z.infer<typeof HandicapAdvisorInputSchema>;

/**
 * Zod schema for the handicap advisor flow output.
 * Provides a suggested handicap and the reasoning for it.
 */
export const HandicapAdvisorOutputSchema = z.object({
  handicap: z.number().describe('The suggested handicap for the player.'),
  reasoning: z
    .string()
    .describe('The reasoning behind the suggested handicap.'),
});
export type HandicapAdvisorOutput = z.infer<typeof HandicapAdvisorOutputSchema>;

/**
* A Genkit flow that provides a handicap suggestion based on player data.
*
* @param {Player} player - The player data object.
* @returns {Promise<HandicapAdvisorOutput>} A promise that resolves to the handicap suggestion and reasoning.
*/
export async function getHandicapSuggestion(player: Player): Promise<HandicapAdvisorOutput> {
    return await handicapAdvisorFlow({ playerData: JSON.stringify(player) });
}


const handicapAdvisorFlow = ai.defineFlow(
  {
    name: 'handicapAdvisorFlow',
    inputSchema: HandicapAdvisorInputSchema,
    outputSchema: HandicapAdvisorOutputSchema,
  },
  async (input) => {
    const { output } = await ai.generate({
      prompt: `Based on this player data: {{playerData}}, provide a handicap suggestion.`,
      model: 'googleai/gemini-2.0-flash',
      output: {
        schema: HandicapAdvisorOutputSchema,
      },
      context: [
          {
              role: 'system',
              content: 'You are a snooker handicap expert. Your role is to analyze player statistics and provide a fair handicap suggestion along with a brief, clear reasoning for your decision. The handicap should be a single numerical value.'
          }
      ],
      config: {
        // Optional configuration for the generation call
      },
    });

    if (!output) {
      throw new Error('No output was generated by the AI model.');
    }
    
    return output;
  }
);
