
--
-- Create a table for public profiles
--
CREATE TABLE public.players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  skill_level TEXT NOT NULL DEFAULT 'Beginner',
  matches_played BIGINT NOT NULL DEFAULT 0,
  win_rate TEXT NOT NULL DEFAULT '0%',
  highest_break BIGINT NOT NULL DEFAULT 0,
  avatar TEXT,
  initials TEXT,
  wins BIGINT DEFAULT 0,
  losses BIGINT DEFAULT 0,
  average_break BIGINT DEFAULT 0,
  achievements JSONB,
  CONSTRAINT "players_name_key" UNIQUE (name)
);

--
-- Create tournaments table
--
CREATE TABLE public.tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    format TEXT NOT NULL,
    players INT NOT NULL,
    status TEXT NOT NULL,
    rules JSONB,
    image TEXT,
    pendingPlayers TEXT[],
    registeredPlayers TEXT[],
    location TEXT,
    winner TEXT,
    bracket JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--
-- Create matches table
--
CREATE TABLE public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    winner TEXT NOT NULL,
    loser TEXT NOT NULL,
    score TEXT NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    media JSONB,
    comments JSONB,
    pending_score JSONB,
    tournament_id BIGINT REFERENCES public.tournaments (id) ON DELETE SET NULL
);

--
-- Create upcoming_matches table
--
CREATE TABLE public.upcoming_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1 TEXT NOT NULL,
    player2 TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    tournament_id BIGINT REFERENCES public.tournaments (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--
-- Create live_matches table
--
CREATE TABLE public.live_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT REFERENCES public.tournaments(id) ON DELETE CASCADE,
    tournament_name TEXT,
    player1 TEXT NOT NULL,
    player2 TEXT NOT NULL,
    score1 INT NOT NULL,
    score2 INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--
-- Create notices table
--
CREATE TABLE public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


--
-- Create notifications table
--
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    date TIMESTAMPTZ NOT NULL,
    link TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


--
-- Create settings table
--
CREATE TABLE public.settings (
    key TEXT PRIMARY KEY,
    value JSONB
);

--
-- Set up Storage for Avatars
--
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', TRUE)
ON CONFLICT (id) DO NOTHING;

--
-- Helper Functions for RLS
--
CREATE OR REPLACE FUNCTION get_user_name()
RETURNS TEXT AS $$
  SELECT auth.jwt()->>'full_name';
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION get_user_email()
RETURNS TEXT AS $$
  SELECT auth.email();
$$ LANGUAGE sql STABLE;

--
-- Set up Row Level Security (RLS)
--
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.upcoming_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to all tables
CREATE POLICY "Allow public read access" ON public.players FOR SELECT USING (TRUE);
CREATE POLICY "Allow public read access" ON public.matches FOR SELECT USING (TRUE);
CREATE POLICY "Allow public read access" ON public.tournaments FOR SELECT USING (TRUE);
CREATE POLICY "Allow public read access" ON public.upcoming_matches FOR SELECT USING (TRUE);
CREATE POLICY "Allow public read access" ON public.live_matches FOR SELECT USING (TRUE);
CREATE POLICY "Allow public read access" ON public.notices FOR SELECT USING (TRUE);
CREATE POLICY "Allow public read access" ON public.settings FOR SELECT USING (TRUE);


-- Allow authenticated users to manage their own data
CREATE POLICY "Allow users to manage their own notifications" ON public.notifications
  FOR ALL
  USING (get_user_name() = user_name)
  WITH CHECK (get_user_name() = user_name);

CREATE POLICY "Allow users to update their own player profile" ON public.players
  FOR UPDATE
  USING (get_user_name() = name)
  WITH CHECK (get_user_name() = name);
  
CREATE POLICY "Allow users to insert their own player profile during signup" ON public.players
  FOR INSERT
  WITH CHECK (get_user_name() = name);

CREATE POLICY "Allow users to manage their tournament applications" ON public.tournaments
  FOR UPDATE
  USING (
    array_position(pendingPlayers, get_user_name()) IS NOT NULL OR
    array_position(registeredPlayers, get_user_name()) IS NOT NULL
  )
  WITH CHECK (
    array_position(pendingPlayers, get_user_name()) IS NOT NULL OR
    array_position(registeredPlayers, get_user_name()) IS NOT NULL
  );

CREATE POLICY "Allow users to update matches they are part of" ON public.matches
  FOR UPDATE
  USING (get_user_name() = winner OR get_user_name() = loser)
  WITH CHECK (get_user_name() = winner OR get_user_name() = loser);


-- Allow admins to do anything
CREATE POLICY "Allow all for admins" ON public.players
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');

CREATE POLICY "Allow all for admins" ON public.matches
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');

CREATE POLICY "Allow all for admins" ON public.tournaments
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');

CREATE POLICY "Allow all for admins" ON public.upcoming_matches
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');

CREATE POLICY "Allow all for admins" ON public.live_matches
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');

CREATE POLICY "Allow all for admins" ON public.notices
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');

CREATE POLICY "Allow all for admins" ON public.notifications
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');
  
CREATE POLICY "Allow all for admins" ON public.settings
  FOR ALL
  USING (get_user_email() = 'imnazelahi@gmail.com')
  WITH CHECK (get_user_email() = 'imnazelahi@gmail.com');


-- Storage policies for avatars
CREATE POLICY "Allow public read on avatars" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "Allow authenticated users to upload avatars" ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

CREATE POLICY "Allow users to update their own avatar" ON storage.objects
  FOR UPDATE
  USING (auth.uid() = owner)
  WITH CHECK (bucket_id = 'avatars');
