
-- Enable HTTP extension
create extension if not exists http with schema extensions;

-- Enable pg_cron for scheduled tasks if needed
create extension if not exists pg_cron with schema extensions;

-- Enable pgcrypto for UUID generation
create extension if not exists pgcrypto with schema extensions;

-- Set up Storage bucket for media
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

-- USERS Table
-- Stores public user data, linked to auth.users
create table if not exists public.users (
    id uuid not null primary key,
    name text,
    email text,
    avatar text,
    role text default 'user'
);
alter table public.users enable row level security;
create policy "Public users are viewable by everyone." on public.users for select using (true);
create policy "Users can insert their own profile." on public.users for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on public.users for update using (auth.uid() = id) with check (auth.uid() = id);
alter table public.users add constraint unique_email unique (email);


-- PLAYERS Table
-- Stores player-specific stats and links to a user profile
create table if not exists public.players (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    skill_level text not null default 'Beginner',
    matches_played integer not null default 0,
    win_rate text not null default '0%',
    highest_break integer not null default 0,
    avatar text,
    initials text,
    wins integer default 0,
    losses integer default 0,
    average_break integer default 0,
    user_id uuid references public.users(id) on delete set null
);
alter table public.players enable row level security;
create policy "Players are viewable by everyone." on public.players for select using (true);
create policy "Authenticated users can create players." on public.players for insert with check (auth.role() = 'authenticated');
create policy "Users can update their own player profile." on public.players for update using (auth.uid() = user_id);
create policy "Admins can update any player." on public.players for update using (exists (select 1 from users where id = auth.uid() and role = 'admin'));
create policy "Admins can delete players." on public.players for delete using (exists (select 1 from users where id = auth.uid() and role = 'admin'));


-- TOURNAMENTS Table
create table if not exists public.tournaments (
    id bigint generated by default as identity primary key,
    name text not null,
    format text not null,
    players integer not null,
    status text not null,
    rules text[],
    image text,
    pendingPlayers text[],
    registeredPlayers text[],
    location text,
    winner text,
    bracket jsonb
);
alter table public.tournaments enable row level security;
create policy "Tournaments are viewable by everyone." on public.tournaments for select using (true);
create policy "Admins can create tournaments." on public.tournaments for insert with check (exists (select 1 from users where id = auth.uid() and role = 'admin'));
create policy "Admins can update tournaments." on public.tournaments for update using (exists (select 1 from users where id = auth.uid() and role = 'admin'));
create policy "Admins can delete tournaments." on public.tournaments for delete using (exists (select 1 from users where id = auth.uid() and role = 'admin'));
create policy "Authenticated users can apply to tournaments (update pendingPlayers)." on public.tournaments for update with check (auth.role() = 'authenticated');


-- MATCHES Table
-- Stores completed match results
create table if not exists public.matches (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    winner text not null,
    loser text not null,
    score text not null,
    date timestamp with time zone not null,
    media text[],
    comments jsonb[],
    pending_score jsonb,
    tournament_id bigint references public.tournaments(id) on delete set null
);
alter table public.matches enable row level security;
create policy "Matches are viewable by everyone." on public.matches for select using (true);
create policy "Authenticated users can create matches." on public.matches for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update matches." on public.matches for update using (auth.role() = 'authenticated');
create policy "Admins can delete matches." on public.matches for delete using (exists (select 1 from users where id = auth.uid() and role = 'admin'));


-- UPCOMING_MATCHES Table
create table if not exists public.upcoming_matches (
    id bigint generated by default as identity primary key,
    player1 text not null,
    player2 text not null,
    date date not null,
    time time not null,
    tournament_id bigint references public.tournaments(id)
);
alter table public.upcoming_matches enable row level security;
create policy "Upcoming matches are viewable by everyone." on public.upcoming_matches for select using (true);
create policy "Admins can manage upcoming matches." on public.upcoming_matches for all using (exists (select 1 from users where id = auth.uid() and role = 'admin'));


-- LIVE_MATCHES Table
create table if not exists public.live_matches (
    id bigint generated by default as identity primary key,
    tournament_id bigint references public.tournaments(id) not null,
    tournament_name text not null,
    player1 text not null,
    player2 text not null,
    score1 integer not null default 0,
    score2 integer not null default 0
);
alter table public.live_matches enable row level security;
create policy "Live matches are viewable by everyone." on public.live_matches for select using (true);
create policy "Admins can manage live matches." on public.live_matches for all using (exists (select 1 from users where id = auth.uid() and role = 'admin'));


-- NOTICES Table
create table if not exists public.notices (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    title text not null,
    content text not null,
    date timestamp with time zone not null
);
alter table public.notices enable row level security;
create policy "Notices are viewable by everyone." on public.notices for select using (true);
create policy "Admins can manage notices." on public.notices for all using (exists (select 1 from users where id = auth.uid() and role = 'admin'));


-- NOTIFICATIONS Table
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null references public.users(id) on delete cascade,
    title text not null,
    description text not null,
    read boolean not null default false,
    date timestamp with time zone not null,
    link text
);
alter table public.notifications enable row level security;
create policy "Users can view their own notifications." on public.notifications for select using (auth.uid() = user_id);
create policy "Users can update their own notifications." on public.notifications for update using (auth.uid() = user_id);
create policy "Users can delete their own notifications." on public.notifications for delete using (auth.uid() = user_id);
-- Note: Inserts are handled by backend/triggers with service_role key.

-- SETTINGS Table (Key-Value store)
create table if not exists public.settings (
    key text primary key,
    value jsonb
);
alter table public.settings enable row level security;
create policy "Settings are publicly readable." on public.settings for select using (true);
create policy "Admins can manage settings." on public.settings for all using (exists (select 1 from users where id = auth.uid() and role = 'admin'));

-- Initial Settings Data
insert into public.settings (key, value)
values 
    ('siteSettings', '{"name": "CueScore", "description": "The ultimate snooker club management app.", "logo": null}'),
    ('tournamentRules', '["Standard WBSA rules apply", "All matches best of 5 frames", "Re-spotted black in case of a tie", "Players must be present 15 minutes before match time"]')
on conflict (key) do nothing;


-- Function and Trigger to create user profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  -- Create a public user profile
  insert into public.users (id, name, email, avatar, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'avatar_url',
    case when new.email = 'imnazelahi@gmail.com' then 'admin' else 'user' end
  );
  
  -- Create a corresponding player profile
  insert into public.players (user_id, name, initials, avatar, skill_level, highest_break)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    (regexp_split_to_array(new.raw_user_meta_data->>'full_name', E'\\s+'))[1][1] || (regexp_split_to_array(new.raw_user_meta_data->>'full_name', E'\\s+'))[2][1],
    new.raw_user_meta_data->>'avatar_url',
    'Beginner',
    0
  );
  return new;
end;
$$;

-- drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Policies for storage bucket
create policy "Media is publicly accessible." on storage.objects
  for select using ( bucket_id = 'media' );

create policy "Authenticated users can upload media." on storage.objects
  for insert with check ( bucket_id = 'media' and auth.role() = 'authenticated' );

create policy "Users can update their own media." on storage.objects
  for update using ( bucket_id = 'media' and auth.uid() = owner );

create policy "Users can delete their own media." on storage.objects
  for delete using ( bucket_id = 'media' and auth.uid() = owner );
