
--
-- Create a table for public players
--
create table players (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  name text not null,
  email text,
  skill_level text not null default 'Beginner'::text,
  matches_played integer not null default 0,
  win_rate text not null default '0%'::text,
  highest_break integer not null default 0,
  avatar text,
  initials text,
  wins integer default 0,
  losses integer default 0,
  average_break integer default 0,
  constraint players_name_key unique (name),
  constraint players_email_key unique (email)
);

--
-- Create a table for tournaments
--
create table tournaments (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    format text not null,
    players integer not null,
    status text not null,
    rules text[],
    image text,
    "pendingPlayers" text[],
    "registeredPlayers" text[],
    location text,
    winner text,
    bracket jsonb
);

--
-- Create a table for notices
--
create table notices (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    title text not null,
    content text not null,
    date timestamp with time zone not null default now()
);

--
-- Create a table for matches
--
create table matches (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    winner text not null,
    loser text not null,
    score text not null,
    date timestamp with time zone not null,
    media text[],
    comments jsonb,
    pending_score jsonb,
    tournament_id bigint,
    constraint matches_tournament_id_fkey foreign key (tournament_id) references tournaments (id)
);

--
-- Create a table for upcoming_matches
--
create table upcoming_matches (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    player1 text not null,
    player2 text not null,
    date date not null,
    time time without time zone not null,
    tournament_id bigint,
    constraint upcoming_matches_tournament_id_fkey foreign key (tournament_id) references tournaments (id)
);

--
-- Create a table for notifications
--
create table notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_name text not null,
    title text not null,
    description text not null,
    read boolean not null default false,
    date timestamp with time zone not null default now(),
    link text
);

--
-- Create a table for settings
--
create table settings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    key text not null,
    value jsonb,
    constraint settings_key_key unique (key)
);

--
-- Create a table for live_matches
--
create table live_matches (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    tournament_id bigint,
    tournament_name text,
    player1 text,
    player2 text,
    score1 integer,
    score2 integer,
    constraint live_matches_tournament_id_fkey foreign key (tournament_id) references tournaments (id)
);


--
-- Set up Row Level Security
--
alter table players enable row level security;
alter table tournaments enable row level security;
alter table notices enable row level security;
alter table matches enable row level security;
alter table upcoming_matches enable row level security;
alter table notifications enable row level security;
alter table settings enable row level security;
alter table live_matches enable row level security;

create policy "Public profiles are viewable by everyone." on players for select using (true);
create policy "Users can insert their own player profile." on players for insert with check (auth.uid() = id or current_user = 'postgres');
create policy "Users can update own profile." on players for update using (auth.uid() = id);

create policy "Tournaments are viewable by everyone." on tournaments for select using (true);
create policy "Admins can create tournaments." on tournaments for insert with check (current_user = 'postgres' or (select email from public.players where id = auth.uid()) = 'admin@gmail.com');
create policy "Admins can update tournaments." on tournaments for update with check (current_user = 'postgres' or (select email from public.players where id = auth.uid()) = 'admin@gmail.com');

create policy "Notices are viewable by everyone." on notices for select using (true);
create policy "Admins can create notices." on notices for insert with check (current_user = 'postgres' or (select email from public.players where id = auth.uid()) = 'admin@gmail.com');

create policy "Matches are viewable by everyone." on matches for select using (true);
create policy "Users can create matches." on matches for insert with check (true);
create policy "Users can update matches." on matches for update using (true);

create policy "Upcoming matches are viewable by everyone." on upcoming_matches for select using (true);
create policy "Admins can manage upcoming matches." on upcoming_matches for all using (current_user = 'postgres' or (select email from public.players where id = auth.uid()) = 'admin@gmail.com');

create policy "Users can view their own notifications." on notifications for select using ((select name from public.players where id = auth.uid()) = user_name);
create policy "Users can update their own notifications." on notifications for update using ((select name from public.players where id = auth.uid()) = user_name);
create policy "Users can delete their own notifications." on notifications for delete using ((select name from public.players where id = auth.uid()) = user_name);
create policy "Users can insert their own notifications." on notifications for insert with check (true);

create policy "Settings are public." on settings for select using (true);
create policy "Admins can update settings." on settings for update with check (current_user = 'postgres' or (select email from public.players where id = auth.uid()) = 'admin@gmail.com');

create policy "Live matches are viewable by everyone." on live_matches for select using (true);
create policy "Admins can manage live matches." on live_matches for all using (current_user = 'postgres' or (select email from public.players where id = auth.uid()) = 'admin@gmail.com');


--
-- Create a function to handle new user creation
--
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.players (id, name, email, initials)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    LEFT(new.raw_user_meta_data->>'full_name', 1) || LEFT(SPLIT_PART(new.raw_user_meta_data->>'full_name', ' ', -1), 1)
  );
  return new;
end;
$$;

--
-- Create a trigger to call the function when a new user signs up
--
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

--
-- Set up Storage!
--

-- Avatars bucket
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

create policy "Avatar images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'avatars' );

create policy "Anyone can upload an avatar."
  on storage.objects for insert
  with check ( bucket_id = 'avatars' );

create policy "Anyone can update their own avatar."
  on storage.objects for update
  using ( auth.uid() = owner )
  with check ( bucket_id = 'avatars' );

-- Media bucket for matches
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

create policy "Media files are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'media' );

create policy "Authenticated users can upload media."
  on storage.objects for insert
  with check ( bucket_id = 'media' and auth.role() = 'authenticated' );

-- Tournament images bucket
insert into storage.buckets (id, name, public)
values ('tournament_images', 'tournament_images', true)
on conflict (id) do nothing;

create policy "Tournament images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'tournament_images' );

create policy "Admins can upload tournament images."
  on storage.objects for insert
  with check ( bucket_id = 'tournament_images' and (select email from public.players where id = auth.uid()) = 'admin@gmail.com' );
  
-- Site logo bucket
insert into storage.buckets (id, name, public)
values ('logos', 'logos', true)
on conflict (id) do nothing;

create policy "Logo images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'logos' );

create policy "Admins can upload logos."
  on storage.objects for insert
  with check ( bucket_id = 'logos' and (select email from public.players where id = auth.uid()) = 'admin@gmail.com' );
  
create policy "Admins can update logos."
  on storage.objects for update
  with check ( bucket_id = 'logos' and (select email from public.players where id = auth.uid()) = 'admin@gmail.com' );
  
--
-- Seed initial data
--
insert into settings (key, value)
values 
  ('siteSettings', '{"name": "CueScore", "description": "The ultimate snooker club management app.", "logo": null}'),
  ('tournamentRules', '["Standard snooker rules apply", "All matches are best of 5 frames", "Players must arrive 15 minutes before their scheduled match time", "The tournament director''s decision is final"]')
on conflict(key) do nothing;

