--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1 (Debian 15.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgsodium; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";


--
-- Name: pg_graphql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";


--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";


--
-- Name: pgjwt; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";


--
-- Name: supabase_vault; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";


--
-- Name: get_user_role(uuid); Type: FUNCTION; Schema: public; Owner: supabase_admin
--

CREATE OR REPLACE FUNCTION "public"."get_user_role"("user_id" "uuid") RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  IF (
    SELECT auth.users.email
    FROM auth.users
    WHERE auth.users.id = user_id
  ) = 'admin@gmail.com' THEN
    RETURN 'admin';
  ELSE
    RETURN 'user';
  END IF;
END;
$$;


ALTER FUNCTION "public"."get_user_role"("user_id" "uuid") OWNER TO "supabase_admin";

--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: postgres
--
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS trigger
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.players (id, name, email, initials, skill_level, matches_played, win_rate, highest_break, wins, losses, average_break, avatar)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    substring(new.raw_user_meta_data->>'full_name' from 1 for 1) || substring(split_part(new.raw_user_meta_data->>'full_name', ' ', 2) from 1 for 1),
    'Beginner',
    0,
    '0%',
    0,
    0,
    0,
    0,
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: live_matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."live_matches" (
    "id" bigint NOT NULL,
    "tournament_id" integer NOT NULL,
    "tournament_name" "text" NOT NULL,
    "player1" "text" NOT NULL,
    "player2" "text" NOT NULL,
    "score1" integer NOT NULL,
    "score2" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."live_matches" OWNER TO "postgres";

--
-- Name: live_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."live_matches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."live_matches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."matches" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "winner" "text" NOT NULL,
    "loser" "text" NOT NULL,
    "score" "text" NOT NULL,
    "date" "date" NOT NULL,
    "media" "json",
    "comments" "json",
    "pending_score" "json",
    "tournament_id" bigint
);


ALTER TABLE "public"."matches" OWNER TO "postgres";

--
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."matches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."matches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."notices" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "title" "text",
    "content" "text",
    "date" "date"
);


ALTER TABLE "public"."notices" OWNER TO "postgres";

--
-- Name: notices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."notices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "user_name" "text" NOT NULL,
    "title" "text",
    "description" "text",
    "read" boolean DEFAULT false,
    "date" "date",
    "link" "text"
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."players" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" NOT NULL,
    "skill_level" "text" DEFAULT 'Beginner'::"text" NOT NULL,
    "matches_played" integer DEFAULT 0 NOT NULL,
    "win_rate" "text" DEFAULT '0%'::"text" NOT NULL,
    "highest_break" integer DEFAULT 0 NOT NULL,
    "avatar" "text",
    "initials" "text",
    "wins" integer,
    "losses" integer,
    "average_break" integer,
    "email" "text"
);


ALTER TABLE "public"."players" OWNER TO "postgres";

--
-- Name: settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."settings" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "key" "text" NOT NULL,
    "value" "json"
);


ALTER TABLE "public"."settings" OWNER TO "postgres";

--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tournaments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."tournaments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text",
    "format" "text",
    "players" integer,
    "status" "text",
    "rules" "json",
    "image" "text",
    "pendingPlayers" "text"[],
    "registeredPlayers" "text"[],
    "location" "text",
    "winner" "text",
    "bracket" "json"
);


ALTER TABLE "public"."tournaments" OWNER TO "postgres";

--
-- Name: tournaments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."tournaments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tournaments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upcoming_matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."upcoming_matches" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "player1" "text" NOT NULL,
    "player2" "text" NOT NULL,
    "date" "date" NOT NULL,
    "time" "text" NOT NULL,
    "tournament_id" bigint
);


ALTER TABLE "public"."upcoming_matches" OWNER TO "postgres";

--
-- Name: upcoming_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."upcoming_matches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."upcoming_matches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: live_matches live_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."live_matches"
    ADD CONSTRAINT "live_matches_pkey" PRIMARY KEY ("id");


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("id");


--
-- Name: notices notices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."notices"
    ADD CONSTRAINT "notices_pkey" PRIMARY KEY ("id");


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");


--
-- Name: players players_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_email_key" UNIQUE ("email");


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");


--
-- Name: settings settings_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_key_key" UNIQUE ("key");


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."settings"
    ADD CONSTRAINT "settings_pkey" PRIMARY KEY ("id");


--
-- Name: tournaments tournaments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."tournaments"
    ADD CONSTRAINT "tournaments_pkey" PRIMARY KEY ("id");


--
-- Name: upcoming_matches upcoming_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."upcoming_matches"
    ADD CONSTRAINT "upcoming_matches_pkey" PRIMARY KEY ("id");


--
-- Name: on_auth_user_created; Type: TRIGGER; Schema: auth; Owner: supabase_auth_admin
--

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


--
-- Name: players players_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");


--
-- Name: live_matches; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."live_matches" ENABLE ROW LEVEL SECURITY;

--
-- Name: matches; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."matches" ENABLE ROW LEVEL SECURITY;

--
-- Name: notices; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."notices" ENABLE ROW LEVEL SECURITY;

--
-- Name: notifications; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;

--
-- Name: players; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;

--
-- Name: settings; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;

--
-- Name: tournaments; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."tournaments" ENABLE ROW LEVEL SECURITY;

--
-- Name: upcoming_matches; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."upcoming_matches" ENABLE ROW LEVEL SECURITY;

--
-- Name: live_matches All access for admin; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "All access for admin" ON "public"."live_matches" FOR ALL TO "authenticated" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text")) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text"));


--
-- Name: matches All access for admin; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "All access for admin" ON "public"."matches" FOR ALL TO "authenticated" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text")) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text"));


--
-- Name: notices All access for admin; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "All access for admin" ON "public"."notices" FOR ALL TO "authenticated" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text")) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text"));


--
-- Name: settings All access for admin; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "All access for admin" ON "public"."settings" FOR ALL TO "authenticated" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text")) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text"));


--
-- Name: tournaments All access for admin; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "All access for admin" ON "public"."tournaments" FOR ALL TO "authenticated" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text")) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text"));


--
-- Name: upcoming_matches All access for admin; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "All access for admin" ON "public"."upcoming_matches" FOR ALL TO "authenticated" USING (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text")) WITH CHECK (("public"."get_user_role"("auth"."uid"()) = 'admin'::"text"));


--
-- Name: notifications Allow authenticated users to manage their own notifications; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Allow authenticated users to manage their own notifications" ON "public"."notifications" FOR ALL TO "authenticated" USING ((( SELECT "auth"."users"."raw_user_meta_data" ->> 'full_name'::"text"
   FROM "auth"."users"
  WHERE ("users"."id" = "auth"."uid"()))) = "user_name") WITH CHECK (("auth"."role"() = 'authenticated'::"text"));


--
-- Name: live_matches Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."live_matches" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: matches Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."matches" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: notices Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."notices" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: players Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."players" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: settings Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."settings" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: tournaments Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."tournaments" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: upcoming_matches Public read access; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Public read access" ON "public"."upcoming_matches" FOR SELECT TO "anon", "authenticated" USING (true);


--
-- Name: matches Users can insert their own matches; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can insert their own matches" ON "public"."matches" FOR INSERT TO "authenticated" WITH CHECK (true);


--
-- Name: players Users can update their own profile; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can update their own profile" ON "public"."players" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));


--
-- Name: tournaments Users can update tournaments to apply; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can update tournaments to apply" ON "public"."tournaments" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);


--
-- Name: SCHEMA "public"; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


--
-- Name: FUNCTION "get_user_role"("user_id" "uuid"); Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "postgres";
GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_role"("user_id" "uuid") TO "service_role";


--
-- Name: FUNCTION "handle_new_user"(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


--
-- Name: TABLE "live_matches"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."live_matches" TO "anon";
GRANT ALL ON TABLE "public"."live_matches" TO "authenticated";
GRANT ALL ON TABLE "public"."live_matches" TO "service_role";


--
-- Name: SEQUENCE "live_matches_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."live_matches_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."live_matches_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."live_matches_id_seq" TO "service_role";


--
-- Name: TABLE "matches"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."matches" TO "anon";
GRANT ALL ON TABLE "public"."matches" TO "authenticated";
GRANT ALL ON TABLE "public"."matches" TO "service_role";


--
-- Name: SEQUENCE "matches_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."matches_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."matches_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."matches_id_seq" TO "service_role";


--
-- Name: TABLE "notices"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."notices" TO "anon";
GRANT ALL ON TABLE "public"."notices" TO "authenticated";
GRANT ALL ON TABLE "public"."notices" TO "service_role";


--
-- Name: SEQUENCE "notices_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."notices_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notices_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notices_id_seq" TO "service_role";


--
-- Name: TABLE "notifications"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";


--
-- Name: SEQUENCE "notifications_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";


--
-- Name: TABLE "players"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."players" TO "anon";
GRANT ALL ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";


--
-- Name: TABLE "settings"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."settings" TO "anon";
GRANT ALL ON TABLE "public"."settings" TO "authenticated";
GRANT ALL ON TABLE "public"."settings" TO "service_role";


--
-- Name: SEQUENCE "settings_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."settings_id_seq" TO "service_role";


--
-- Name: TABLE "tournaments"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."tournaments" TO "anon";
GRANT ALL ON TABLE "public"."tournaments" TO "authenticated";
GRANT ALL ON TABLE "public"."tournaments" TO "service_role";


--
-- Name: SEQUENCE "tournaments_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."tournaments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tournaments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tournaments_id_seq" TO "service_role";


--
-- Name: TABLE "upcoming_matches"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE "public"."upcoming_matches" TO "anon";
GRANT ALL ON TABLE "public"."upcoming_matches" TO "authenticated";
GRANT ALL ON TABLE "public"."upcoming_matches" TO "service_role";


--
-- Name: SEQUENCE "upcoming_matches_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE "public"."upcoming_matches_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."upcoming_matches_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."upcoming_matches_id_seq" TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

--
-- Setup storage buckets
--

insert into storage.buckets
  (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 1048576, '{"image/jpeg","image/png"}')
on conflict (id) do nothing;

CREATE POLICY "Avatar images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can upload an avatar."
  on storage.objects for insert
  with check ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can update their own avatar."
  on storage.objects for update
  using ( auth.uid() = owner )
  with check ( bucket_id = 'avatars' );


--
-- PostgreSQL database dump complete
--
