--
-- Create a table for public profiles
--
create table if not exists players (
  id uuid not null primary key,
  created_at timestamp with time zone default now(),
  name text,
  email text,
  skill_level text default 'Beginner'::text,
  matches_played integer default 0,
  win_rate text default '0%'::text,
  highest_break integer default 0,
  avatar text,
  initials text,
  wins integer default 0,
  losses integer default 0,
  average_break integer default 0
);

--
-- Create a table for matches
--
create table if not exists matches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  winner text,
  loser text,
  score text,
  date timestamp with time zone,
  media jsonb,
  comments jsonb,
  pending_score jsonb,
  tournament_id bigint
);

--
-- Create a table for tournaments
--
create table if not exists tournaments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text,
  format text,
  players integer,
  status text,
  rules text[],
  image text,
  "pendingPlayers" text[],
  "registeredPlayers" text[],
  location text,
  winner text,
  bracket jsonb,
  tournament_id bigint
);

--
-- Create a table for notices
--
create table if not exists notices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  title text,
  content text,
  date timestamp with time zone
);

--
-- Create a table for upcoming matches
--
create table if not exists upcoming_matches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  player1 text,
  player2 text,
  date date,
  time time without time zone,
  tournament_id bigint
);

--
-- Create a table for live matches
--
create table if not exists live_matches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  tournament_id bigint,
  tournament_name text,
  player1 text,
  player2 text,
  score1 integer,
  score2 integer
);

--
-- Create a table for notifications
--
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_name text,
  title text,
  description text,
  read boolean default false,
  date timestamp with time zone,
  link text
);

--
-- Create a table for settings
--
create table if not exists settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  key text unique,
  value jsonb
);


--
-- Define a function to get user role
--
create or replace function get_user_role(user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select (raw_user_meta_data->>'isAdmin')::boolean from auth.users where id = user_id) then
    return 'admin';
  else
    return 'user';
  end if;
end;
$$;


--
-- Create a function to handle new user creation
--
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.players (id, name, email, initials)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    substring(new.raw_user_meta_data->>'full_name' from 1 for 1) || substring(split_part(new.raw_user_meta_data->>'full_name', ' ', 2) from 1 for 1)
  );
  return new;
end;
$$;

--
-- Create a trigger to call the handle_new_user function on new user creation
--
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


--
-- Set up Storage!
--
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

--
-- Set up RLS policies for storage
--
-- Avatars can be read by anyone
create policy "anyone_can_read_avatars"
on storage.objects for select
to public
using ( bucket_id = 'avatars' );

-- Avatars can only be uploaded by the owner of the avatar
create policy "user_can_upload_avatar"
on storage.objects for insert
to public
with check (
  bucket_id = 'avatars'
  and owner = auth.uid()
);

create policy "user_can_update_avatar"
on storage.objects for update
to public
using (
  bucket_id = 'avatars'
  and owner = auth.uid()
);

--
-- Set up Row Level Security (RLS) policies
--
-- Players
alter table players enable row level security;
drop policy if exists "players_are_public" on players;
create policy "players_are_public" on players for select to public using (true);
drop policy if exists "users_can_update_own_player" on players;
create policy "users_can_update_own_player" on players for update to public using (auth.uid() = id);
drop policy if exists "admins_can_do_anything_on_players" on players;
create policy "admins_can_do_anything_on_players" on players for all to public using (get_user_role(auth.uid()) = 'admin');


-- Matches
alter table matches enable row level security;
drop policy if exists "matches_are_public" on matches;
create policy "matches_are_public" on matches for select to public using (true);
drop policy if exists "users_can_manage_own_matches" on matches;
create policy "users_can_manage_own_matches" on matches for all to public using (
  auth.uid() in (select id from players where name = winner or name = loser)
);
drop policy if exists "admins_can_do_anything_on_matches" on matches;
create policy "admins_can_do_anything_on_matches" on matches for all to public using (get_user_role(auth.uid()) = 'admin');

-- Tournaments
alter table tournaments enable row level security;
drop policy if exists "tournaments_are_public" on tournaments;
create policy "tournaments_are_public" on tournaments for select to public using (true);
drop policy if exists "admins_can_do_anything_on_tournaments" on tournaments;
create policy "admins_can_do_anything_on_tournaments" on tournaments for all to public using (get_user_role(auth.uid()) = 'admin');

-- Notices
alter table notices enable row level security;
drop policy if exists "notices_are_public" on notices;
create policy "notices_are_public" on notices for select to public using (true);
drop policy if exists "admins_can_do_anything_on_notices" on notices;
create policy "admins_can_do_anything_on_notices" on notices for all to public using (get_user_role(auth.uid()) = 'admin');

-- Upcoming Matches
alter table upcoming_matches enable row level security;
drop policy if exists "upcoming_matches_are_public" on upcoming_matches;
create policy "upcoming_matches_are_public" on upcoming_matches for select to public using (true);
drop policy if exists "admins_can_do_anything_on_upcoming_matches" on upcoming_matches;
create policy "admins_can_do_anything_on_upcoming_matches" on upcoming_matches for all to public using (get_user_role(auth.uid()) = 'admin');

-- Live Matches
alter table live_matches enable row level security;
drop policy if exists "live_matches_are_public" on live_matches;
create policy "live_matches_are_public" on live_matches for select to public using (true);
drop policy if exists "admins_can_do_anything_on_live_matches" on live_matches;
create policy "admins_can_do_anything_on_live_matches" on live_matches for all to public using (get_user_role(auth.uid()) = 'admin');

-- Notifications
alter table notifications enable row level security;
drop policy if exists "users_can_view_own_notifications" on notifications;
create policy "users_can_view_own_notifications" on notifications for select to public using (
  (select id from players where name = user_name) = auth.uid()
);
drop policy if exists "users_can_manage_own_notifications" on notifications;
create policy "users_can_manage_own_notifications" on notifications for update to public using (
  (select id from players where name = user_name) = auth.uid()
);
drop policy if exists "backend_can_insert_notifications" on notifications;
create policy "backend_can_insert_notifications" on notifications for insert to public with check (true);
drop policy if exists "admins_can_do_anything_on_notifications" on notifications;
create policy "admins_can_do_anything_on_notifications" on notifications for all to public using (get_user_role(auth.uid()) = 'admin');


-- Settings
alter table settings enable row level security;
drop policy if exists "settings_are_public" on settings;
create policy "settings_are_public" on settings for select to public using (true);
drop policy if exists "admins_can_do_anything_on_settings" on settings;
create policy "admins_can_do_anything_on_settings" on settings for all to public using (
  (select email from auth.users where id = auth.uid()) = 'admin@gmail.com'
) with check (
  (select email from auth.users where id = auth.uid()) = 'admin@gmail.com'
);
