--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: is_admin(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT (auth.jwt()->>'email') = 'admin@gmail.com';
$$;

--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: -
--
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
begin
  -- This is a placeholder for invoking an edge function.
  -- In a real Supabase project, you would uncomment the following lines and ensure the edge function is deployed.
  /*
  perform net.http_post(
    url:='https://<project_ref>.supabase.co/functions/v1/create-player-profile',
    headers:='{"Content-Type":"application/json", "Authorization": "Bearer " || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}',
    body:=json_build_object('record', new)
  );
  */
  -- For local development, we directly insert into players table, bypassing RLS as SECURITY DEFINER.
  insert into public.players (id, name, email, initials, skill_level, matches_played, win_rate, highest_break, wins, losses, average_break)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    substring(new.raw_user_meta_data->>'full_name' from 1 for 1) || substring(split_part(new.raw_user_meta_data->>'full_name', ' ', 2) from 1 for 1),
    'Beginner',
    0,
    '0%',
    0,
    0,
    0,
    0
  );
  return new;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    id uuid PRIMARY KEY REFERENCES auth.users(id),
    name text NOT NULL,
    email text,
    skill_level text DEFAULT 'Beginner'::text NOT NULL,
    matches_played integer DEFAULT 0 NOT NULL,
    win_rate text DEFAULT '0%'::text NOT NULL,
    highest_break integer DEFAULT 0 NOT NULL,
    avatar text,
    initials text,
    wins integer DEFAULT 0,
    losses integer DEFAULT 0,
    average_break integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tournaments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tournaments (
    id bigint NOT NULL,
    name text NOT NULL,
    format text DEFAULT 'Knockout'::text NOT NULL,
    players integer DEFAULT 8 NOT NULL,
    status text DEFAULT 'Upcoming'::text NOT NULL,
    rules text[],
    image text,
    pending_players text[],
    registered_players text[],
    location text,
    winner text,
    bracket jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tournaments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tournaments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tournaments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matches (
    id bigint NOT NULL,
    winner text NOT NULL,
    loser text NOT NULL,
    score text NOT NULL,
    date timestamp with time zone DEFAULT now() NOT NULL,
    media text[],
    comments jsonb,
    pending_score jsonb,
    tournament_id bigint REFERENCES public.tournaments(id)
);

--
-- Name: matches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: upcoming_matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upcoming_matches (
    id bigint NOT NULL,
    player1 text NOT NULL,
    player2 text NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    tournament_id bigint REFERENCES public.tournaments(id)
);

--
-- Name: upcoming_matches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.upcoming_matches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upcoming_matches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: live_matches; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.live_matches AS
 SELECT um.id,
    um.tournament_id,
    t.name AS tournament_name,
    um.player1,
    um.player2,
    0 AS score1,
    0 AS score2
   FROM (public.upcoming_matches um
     LEFT JOIN public.tournaments t ON ((um.tournament_id = t.id)))
  WHERE ((um.date = CURRENT_DATE) AND (um."time" <= CURRENT_TIME));


--
-- Name: notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notices (
    id bigint NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    date timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_name text NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    read boolean DEFAULT false NOT NULL,
    date timestamp with time zone DEFAULT now() NOT NULL,
    link text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    id bigint NOT NULL,
    key text NOT NULL UNIQUE,
    value jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- RLS policies
--

ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view player profiles" ON public.players FOR SELECT USING (true);
CREATE POLICY "Users can insert their own player profile" ON public.players FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own player profile" ON public.players FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Admins can manage all player profiles" ON public.players FOR ALL USING (is_admin()) WITH CHECK (is_admin());

ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all matches" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create matches" ON public.matches FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can update matches they are in" ON public.matches FOR UPDATE USING (is_admin() OR (auth.jwt() ->> 'email' IN (SELECT email FROM public.players WHERE name = winner OR name = loser)));

ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all tournaments" ON public.tournaments FOR SELECT USING (true);
CREATE POLICY "Admins can manage tournaments" ON public.tournaments FOR ALL USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Authenticated users can update tournament applications" ON public.tournaments FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own notifications" ON public.notifications FOR SELECT USING ((auth.jwt() ->> 'email' IN (SELECT email FROM public.players WHERE name = user_name)));
CREATE POLICY "Users can update their own notifications" ON public.notifications FOR UPDATE USING ((auth.jwt() ->> 'email' IN (SELECT email FROM public.players WHERE name = user_name)));
CREATE POLICY "Authenticated users can insert notifications" ON public.notifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can delete their own notifications" ON public.notifications FOR DELETE USING ((auth.jwt() ->> 'email' IN (SELECT email FROM public.players WHERE name = user_name)));

ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all notices" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Admins can manage notices" ON public.notices FOR ALL USING (is_admin()) WITH CHECK (is_admin());

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Admins can manage settings" ON public.settings FOR ALL USING (is_admin()) WITH CHECK (is_admin());

ALTER TABLE public.upcoming_matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all upcoming matches" ON public.upcoming_matches FOR SELECT USING (true);
CREATE POLICY "Admins can manage upcoming matches" ON public.upcoming_matches FOR ALL USING (is_admin()) WITH CHECK (is_admin());

--
-- Name: on_auth_user_created; Type: TRIGGER; Schema: auth; Owner: -
--
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


--
-- PostgreSQL database dump complete
--
