-- Create the is_admin function
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN (auth.jwt()->>'email') = 'admin@gmail.com';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create the players table
CREATE TABLE public.players (
    id uuid NOT NULL,
    name text NOT NULL,
    email text,
    skill_level text DEFAULT 'Beginner'::text NOT NULL,
    matches_played integer DEFAULT 0 NOT NULL,
    win_rate text DEFAULT '0%'::text NOT NULL,
    highest_break integer DEFAULT 0 NOT NULL,
    avatar text,
    initials text,
    wins integer DEFAULT 0,
    losses integer DEFAULT 0,
    average_break integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.players ADD CONSTRAINT players_pkey PRIMARY KEY (id);
ALTER TABLE public.players ADD CONSTRAINT players_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Create tournaments table
CREATE TABLE public.tournaments (
    id bigint generated by default as identity,
    name text not null,
    format text not null,
    players integer not null,
    status text not null,
    rules text[],
    image text,
    pendingPlayers text[],
    registeredPlayers text[],
    location text,
    winner text,
    bracket jsonb,
    primary key (id)
);

-- Create matches table
CREATE TABLE public.matches (
    id bigint generated by default as identity,
    winner text not null,
    loser text not null,
    score text not null,
    date timestamp with time zone not null,
    media text[],
    comments jsonb,
    pending_score jsonb,
    tournament_id bigint,
    primary key (id),
    foreign key (tournament_id) references tournaments (id)
);

-- Create upcoming_matches table
CREATE TABLE public.upcoming_matches (
    id bigint generated by default as identity,
    player1 text not null,
    player2 text not null,
    date date not null,
    time time without time zone not null,
    tournament_id bigint,
    primary key (id),
    foreign key (tournament_id) references tournaments (id)
);

-- Create settings table
CREATE TABLE public.settings (
    id bigint generated by default as identity,
    key text not null,
    value jsonb,
    primary key (id),
    unique (key)
);

-- Create notices table
CREATE TABLE public.notices (
    id bigint generated by default as identity,
    title text not null,
    content text not null,
    date timestamp with time zone not null,
    created_at timestamp with time zone default now(),
    primary key (id)
);

-- Create notifications table
CREATE TABLE public.notifications (
    id bigint generated by default as identity,
    user_name text not null,
    title text not null,
    description text not null,
    read boolean default false,
    date timestamp with time zone not null,
    link text,
    created_at timestamp with time zone default now(),
    primary key (id)
);

-- Create the live_matches view
CREATE OR REPLACE VIEW public.live_matches AS
 SELECT um.id,
    um.tournament_id,
    t.name AS tournament_name,
    um.player1,
    um.player2,
    floor(random() * 5::double precision) AS score1,
    floor(random() * 5::double precision) AS score2
   FROM (public.upcoming_matches um
     JOIN public.tournaments t ON ((um.tournament_id = t.id)))
  WHERE ((t.status = 'In Progress'::text) AND (um.date <= now()));


-- PLAYER AVATARS BUCKET
insert into storage.buckets (id, name, public)
values ('player_avatars', 'player_avatars', true);

-- RLS Policies for players table
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.players FOR SELECT USING (true);
CREATE POLICY "Allow individual user to update their own profile" ON public.players FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow individual user to insert their own profile" ON public.players FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow admin full access" ON public.players FOR ALL USING (public.is_admin());

-- RLS Policies for avatars bucket
CREATE POLICY "Allow public read access to avatars" ON storage.objects FOR SELECT TO authenticated, anon USING (bucket_id = 'player_avatars');
CREATE POLICY "Allow user to manage their own avatar" ON storage.objects FOR INSERT WITH CHECK (auth.uid() = owner_id AND bucket_id = 'player_avatars');
CREATE POLICY "Allow user to update their own avatar" ON storage.objects FOR UPDATE USING (auth.uid() = owner_id AND bucket_id = 'player_avatars');
CREATE POLICY "Allow user to delete their own avatar" ON storage.objects FOR DELETE USING (auth.uid() = owner_id AND bucket_id = 'player_avatars');
CREATE POLICY "Allow admin full access to avatars" ON storage.objects FOR ALL USING (public.is_admin() AND bucket_id = 'player_avatars');

-- RLS Policies for other tables
ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.tournaments FOR SELECT USING (true);
CREATE POLICY "Allow admin full access on tournaments" ON public.tournaments FOR ALL USING (public.is_admin());
CREATE POLICY "Allow users to apply to tournaments" ON public.tournaments FOR UPDATE
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (
        (pendingplayers IS NOT NULL AND array_position(pendingplayers, (select raw_user_meta_data->>'full_name' from auth.users where id = auth.uid())) IS NOT NULL) OR
        (registeredplayers IS NOT NULL AND array_position(registeredplayers, (select raw_user_meta_data->>'full_name' from auth.users where id = auth.uid())) IS NOT NULL)
    );

ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Allow admin full access on matches" ON public.matches FOR ALL USING (public.is_admin());
CREATE POLICY "Allow users to update their own matches" ON public.matches FOR UPDATE
    USING (
        auth.uid() = (select id from public.players where name = winner) OR
        auth.uid() = (select id from public.players where name = loser)
    );
CREATE POLICY "Allow users to create matches" ON public.matches FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

ALTER TABLE public.upcoming_matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.upcoming_matches FOR SELECT USING (true);
CREATE POLICY "Allow admin full access on upcoming_matches" ON public.upcoming_matches FOR ALL USING (public.is_admin());

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow admin full access on settings" ON public.settings FOR ALL USING (public.is_admin());

ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Allow admin full access on notices" ON public.notices FOR ALL USING (public.is_admin());

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow user to see their own notifications" ON public.notifications FOR SELECT USING (user_name = (select raw_user_meta_data->>'full_name' from auth.users where id = auth.uid()));
CREATE POLICY "Allow user to update their own notifications" ON public.notifications FOR UPDATE USING (user_name = (select raw_user_meta_data->>'full_name' from auth.users where id = auth.uid()));
CREATE POLICY "Allow user to delete their own notifications" ON public.notifications FOR DELETE USING (user_name = (select raw_user_meta_data->>'full_name' from auth.users where id = auth.uid()));
CREATE POLICY "Allow backend to insert notifications" ON public.notifications FOR INSERT WITH CHECK (true);
