-- Custom types
CREATE TYPE skill_level AS ENUM ('Beginner', 'Intermediate', 'Pro');
CREATE TYPE tournament_format AS ENUM ('Knockout', 'League', 'Round Robin');
CREATE TYPE tournament_status AS ENUM ('Upcoming', 'In Progress', 'Finished');

-- Helper function to check if a user is an admin
CREATE OR REPLACE FUNCTION is_admin(user_email TEXT)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN user_email = 'admin@gmail.com';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create a table for public players
CREATE TABLE players (
    id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    skill_level skill_level NOT NULL DEFAULT 'Beginner',
    matches_played INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    win_rate TEXT NOT NULL DEFAULT '0%',
    highest_break INTEGER NOT NULL DEFAULT 0,
    average_break INTEGER,
    avatar TEXT,
    initials TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a table for tournaments
CREATE TABLE tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    format tournament_format NOT NULL,
    players INTEGER NOT NULL,
    status tournament_status NOT NULL,
    rules TEXT[],
    image TEXT,
    pendingPlayers TEXT[],
    registeredPlayers TEXT[],
    location TEXT,
    winner TEXT,
    bracket JSONB
);

-- Create a table for matches
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    winner TEXT NOT NULL,
    loser TEXT NOT NULL,
    score TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    media TEXT[],
    comments JSONB,
    pending_score JSONB,
    tournament_id BIGINT REFERENCES tournaments(id)
);

-- Create a table for upcoming matches
CREATE TABLE upcoming_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1 TEXT NOT NULL,
    player2 TEXT NOT NULL,
    date DATE NOT NULL,
    "time" TIME NOT NULL,
    tournament_id BIGINT REFERENCES tournaments(id)
);

-- Create a table for notices
CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a table for notifications
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a table for settings
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value JSONB
);

-- Create a VIEW for live matches
CREATE VIEW live_matches AS
SELECT
    um.id,
    um.tournament_id,
    t.name AS tournament_name,
    um.player1,
    um.player2,
    -- Simulate live scores for demonstration
    floor(random() * 5)::int AS score1,
    floor(random() * 5)::int AS score2
FROM
    upcoming_matches um
JOIN
    tournaments t ON um.tournament_id = t.id
WHERE
    t.status = 'In Progress' AND um.date = CURRENT_DATE;


-- Set up Row Level Security (RLS)
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE upcoming_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Policies for players
CREATE POLICY "Allow public read-only access to players" ON players FOR SELECT USING (true);
CREATE POLICY "Allow users to update their own player profile" ON players FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow admin full access to players" ON players FOR ALL USING (is_admin(auth.email()));

-- Policies for matches
CREATE POLICY "Allow public read-only access to matches" ON matches FOR SELECT USING (true);
CREATE POLICY "Allow logged-in users to create matches" ON matches FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow admin full access to matches" ON matches FOR ALL USING (is_admin(auth.email()));

-- Policies for tournaments
CREATE POLICY "Allow public read-only access to tournaments" ON tournaments FOR SELECT USING (true);
CREATE POLICY "Allow admin full access to tournaments" ON tournaments FOR ALL USING (is_admin(auth.email()));

-- Policies for upcoming_matches
CREATE POLICY "Allow public read-only access to upcoming_matches" ON upcoming_matches FOR SELECT USING (true);
CREATE POLICY "Allow admin full access to upcoming_matches" ON upcoming_matches FOR ALL USING (is_admin(auth.email()));

-- Policies for notices
CREATE POLICY "Allow public read-only access to notices" ON notices FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage notices" ON notices FOR ALL USING (is_admin(auth.email()));

-- Policies for notifications
CREATE POLICY "Allow users to see their own notifications" ON notifications FOR SELECT USING (auth.jwt()->>'full_name' = user_name);
CREATE POLICY "Allow users to update their own notifications" ON notifications FOR UPDATE USING (auth.jwt()->>'full_name' = user_name);

-- Policies for settings
CREATE POLICY "Allow public read-only access to settings" ON settings FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage settings" ON settings FOR ALL USING (is_admin(auth.email()));

-- Set up Storage bucket and policies for avatars
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Avatar images are publicly accessible." ON storage.objects
FOR SELECT USING (bucket_id = 'avatars');

CREATE POLICY "Anyone can upload an avatar." ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "Anyone can update their own avatar." ON storage.objects
FOR UPDATE USING (auth.uid() = owner) WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "Admins can manage all avatars." ON storage.objects
FOR ALL USING (is_admin(auth.email()));
