
-- Enable HTTP extension
create extension if not exists http with schema extensions;

-- Enable UUID functions
create extension if not exists "uuid-ossp" with schema extensions;

-- Create the players table
create table if not exists public.players (
    id uuid not null primary key,
    name text not null,
    email text unique,
    skill_level text default 'Beginner'::text not null,
    matches_played integer default 0 not null,
    win_rate text default '0%'::text not null,
    highest_break integer default 0 not null,
    avatar text,
    initials text,
    wins integer default 0,
    losses integer default 0,
    average_break integer default 0,
    created_at timestamp with time zone default now() not null
);
alter table public.players enable row level security;

-- Create the matches table
create table if not exists public.matches (
    id bigint generated by default as identity primary key,
    winner text not null,
    loser text not null,
    score text not null,
    date timestamp with time zone not null,
    media jsonb,
    comments jsonb,
    pending_score jsonb,
    tournament_id bigint
);
alter table public.matches enable row level security;

-- Create the upcoming_matches table
create table if not exists public.upcoming_matches (
    id bigint generated by default as identity primary key,
    player1 text not null,
    player2 text not null,
    date date not null,
    "time" time without time zone not null,
    tournament_id bigint
);
alter table public.upcoming_matches enable row level security;

-- Create the live_matches table
create table if not exists public.live_matches (
    id bigint generated by default as identity primary key,
    tournament_id bigint not null,
    tournament_name text not null,
    player1 text not null,
    player2 text not null,
    score1 integer not null,
    score2 integer not null
);
alter table public.live_matches enable row level security;

-- Create the tournaments table
create table if not exists public.tournaments (
    id bigint generated by default as identity primary key,
    name text not null,
    format text not null,
    players integer not null,
    status text not null,
    rules jsonb,
    image text,
    pendingPlayers jsonb,
    registeredPlayers jsonb,
    location text,
    winner text,
    bracket jsonb
);
alter table public.tournaments enable row level security;

-- Create the notifications table
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_name text not null,
    title text not null,
    description text not null,
    read boolean default false not null,
    date timestamp with time zone not null,
    link text,
    created_at timestamp with time zone default now() not null
);
alter table public.notifications enable row level security;

-- Create the notices table
create table if not exists public.notices (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    date timestamp with time zone not null,
    created_at timestamp with time zone default now() not null
);
alter table public.notices enable row level security;

-- Create the settings table
create table if not exists public.settings (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value jsonb,
    created_at timestamp with time zone default now()
);
alter table public.settings enable row level security;


-- Drop the existing trigger and function if they exist, in the correct order
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

-- Create function to create a player profile when a new user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.players (id, name, email, initials, skill_level, matches_played, wins, losses, win_rate, highest_break, average_break, avatar)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    substring(new.raw_user_meta_data->>'full_name' from 1 for 1) || substring(split_part(new.raw_user_meta_data->>'full_name', ' ', 2) from 1 for 1),
    'Beginner',
    0,
    0,
    0,
    '0%',
    0,
    0,
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;

-- Create trigger to call the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- RLS Policies
-- Players Table
drop policy if exists "Enable read access for all users" on public.players;
create policy "Enable read access for all users" on public.players for select using (true);
drop policy if exists "Enable update for users based on email" on public.players;
create policy "Enable update for users based on email" on public.players for update using (auth.uid() = id);
drop policy if exists "Enable insert for authenticated users" on public.players;
create policy "Enable insert for authenticated users" on public.players for insert with check (auth.role() = 'authenticated');
drop policy if exists "Admins can do everything" on public.players;
create policy "Admins can do everything" on public.players for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Matches Table
drop policy if exists "Enable read access for all users" on public.matches;
create policy "Enable read access for all users" on public.matches for select using (true);
drop policy if exists "Enable insert for authenticated users" on public.matches;
create policy "Enable insert for authenticated users" on public.matches for insert with check (auth.role() = 'authenticated');
drop policy if exists "Enable update for authenticated users" on public.matches;
create policy "Enable update for authenticated users" on public.matches for update using (auth.role() = 'authenticated');
drop policy if exists "Admins can do everything" on public.matches;
create policy "Admins can do everything" on public.matches for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Upcoming Matches Table
drop policy if exists "Enable read access for all users" on public.upcoming_matches;
create policy "Enable read access for all users" on public.upcoming_matches for select using (true);
drop policy if exists "Admins can do everything" on public.upcoming_matches;
create policy "Admins can do everything" on public.upcoming_matches for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Live Matches Table
drop policy if exists "Enable read access for all users" on public.live_matches;
create policy "Enable read access for all users" on public.live_matches for select using (true);
drop policy if exists "Admins can do everything" on public.live_matches;
create policy "Admins can do everything" on public.live_matches for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Tournaments Table
drop policy if exists "Enable read access for all users" on public.tournaments;
create policy "Enable read access for all users" on public.tournaments for select using (true);
drop policy if exists "Enable insert for authenticated users" on public.tournaments;
create policy "Enable insert for authenticated users" on public.tournaments for insert with check (auth.role() = 'authenticated');
drop policy if exists "Enable update for authenticated users" on public.tournaments;
create policy "Enable update for authenticated users" on public.tournaments for update using (auth.role() = 'authenticated');
drop policy if exists "Admins can do everything" on public.tournaments;
create policy "Admins can do everything" on public.tournaments for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Notifications Table
drop policy if exists "Enable read for specific users" on public.notifications;
create policy "Enable read for specific users" on public.notifications for select using (auth.jwt() ->> 'email' = (select email from players where name = user_name limit 1) or auth.jwt() ->> 'email' = 'admin@gmail.com');
drop policy if exists "Enable insert for authenticated users" on public.notifications;
create policy "Enable insert for authenticated users" on public.notifications for insert with check (auth.role() = 'authenticated');
drop policy if exists "Enable update for specific users" on public.notifications;
create policy "Enable update for specific users" on public.notifications for update using (auth.jwt() ->> 'email' = (select email from players where name = user_name limit 1));
drop policy if exists "Enable delete for specific users" on public.notifications;
create policy "Enable delete for specific users" on public.notifications for delete using (auth.jwt() ->> 'email' = (select email from players where name = user_name limit 1));
drop policy if exists "Admins can do everything" on public.notifications;
create policy "Admins can do everything" on public.notifications for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Notices Table
drop policy if exists "Enable read access for all users" on public.notices;
create policy "Enable read access for all users" on public.notices for select using (true);
drop policy if exists "Admins can do everything" on public.notices;
create policy "Admins can do everything" on public.notices for all using (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Settings Table
drop policy if exists "Enable read access for all users" on public.settings;
create policy "Enable read access for all users" on public.settings for select using (true);
drop policy if exists "Admins can insert and update settings" on public.settings;
create policy "Admins can insert and update settings" for all on public.settings using (auth.jwt() ->> 'email' = 'admin@gmail.com') with check (auth.jwt() ->> 'email' = 'admin@gmail.com');

-- Seed initial data
insert into public.settings (key, value)
values
  ('siteSettings', '{"name": "CueScore", "description": "The ultimate snooker club management app.", "logo": null}'),
  ('tournamentRules', '["Best of 3 frames", "Foul and a miss rule applies", "Standard snooker rules", "Respect your opponent", "Winner reports score", "Loser buys drinks"]'::jsonb)
on conflict (key) do nothing;
