
-- Drop policies and functions in reverse order of creation
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."settings";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."settings";
DROP POLICY IF EXISTS "Enable delete for users based on user_name" ON "public"."notifications";
DROP POLICY IF EXISTS "Enable update for users based on user_name" ON "public"."notifications";
DROP POLICY IF EXISTS "Enable insert for users based on user_name" ON "public"."notifications";
DROP POLICY IF EXISTS "Enable read access for user based on user_name" ON "public"."notifications";
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."notices";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."notices";
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."tournaments";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."tournaments";
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."upcoming_matches";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."upcoming_matches";
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."matches";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."matches";
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."players";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."players";
DROP POLICY IF EXISTS "Enable all access for admin users" ON "public"."live_matches";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."live_matches";

-- Drop the trigger before the function
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Now drop the function
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Recreate tables
CREATE TABLE IF NOT EXISTS public.players (
    id uuid NOT NULL PRIMARY KEY,
    name character varying NOT NULL,
    email character varying,
    skill_level character varying DEFAULT 'Beginner'::character varying,
    matches_played integer DEFAULT 0,
    win_rate character varying DEFAULT '0%'::character varying,
    highest_break integer DEFAULT 0,
    avatar character varying,
    initials character varying,
    wins integer DEFAULT 0,
    losses integer DEFAULT 0,
    average_break integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT players_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    winner character varying NOT NULL,
    loser character varying NOT NULL,
    score character varying NOT NULL,
    date timestamp with time zone NOT NULL,
    media jsonb,
    comments jsonb,
    pending_score jsonb,
    tournament_id bigint
);

CREATE TABLE IF NOT EXISTS public.tournaments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying NOT NULL,
    format character varying,
    players integer,
    status character varying,
    rules jsonb,
    image text,
    "pendingPlayers" jsonb,
    "registeredPlayers" jsonb,
    location character varying,
    winner character varying,
    bracket jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.upcoming_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1 character varying,
    player2 character varying,
    date date,
    "time" time without time zone,
    tournament_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.live_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id bigint,
    tournament_name character varying,
    player1 character varying,
    player2 character varying,
    score1 integer,
    score2 integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying,
    content text,
    date timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key character varying UNIQUE,
    value jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name character varying,
    title character varying,
    description text,
    read boolean,
    date timestamp with time zone,
    link character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Recreate the function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.players (id, name, email, initials, skill_level, matches_played, win_rate, highest_break, wins, losses, average_break)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.email,
    SUBSTRING(NEW.raw_user_meta_data->>'full_name' FROM 1 FOR 1) || SUBSTRING(SPLIT_PART(NEW.raw_user_meta_data->>'full_name', ' ', 2) FROM 1 FOR 1),
    'Beginner',
    0,
    '0%',
    0,
    0,
    0,
    0
  );
  RETURN NEW;
END;
$$;

-- Recreate the trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Recreate policies with corrected logic
CREATE POLICY "Enable read access for all users" ON "public"."players" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."players" FOR ALL USING (auth.email() = 'admin@gmail.com') WITH CHECK (auth.email() = 'admin@gmail.com');

CREATE POLICY "Enable read access for all users" ON "public"."matches" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."matches" FOR ALL USING (auth.email() = 'admin@gmail.com') WITH CHECK (auth.email() = 'admin@gmail.com');

CREATE POLICY "Enable read access for all users" ON "public"."upcoming_matches" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."upcoming_matches" FOR ALL USING (auth.email() = 'admin@gmail.com') WITH CHECK (auth.email() = 'admin@gmail.com');

CREATE POLICY "Enable read access for all users" ON "public"."tournaments" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."tournaments" FOR ALL USING (auth.email() = 'admin@gmail.com') WITH CHECK (auth.email() = 'admin@gmail.com');

CREATE POLICY "Enable read access for all users" ON "public"."notices" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."notices" FOR ALL USING (auth.email() = 'admin@gmail.com') WITH CHECK (auth.email() = 'admin@gmail.com');

CREATE POLICY "Enable read access for all users" ON "public"."live_matches" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."live_matches" FOR ALL USING (auth.email() = 'admin@gmail.com') WITH CHECK (auth.email() = 'admin@gmail.com');

-- Corrected Settings Policies
CREATE POLICY "Enable read access for all users" ON "public"."settings" FOR SELECT USING (true);
CREATE POLICY "Enable all access for admin users" ON "public"."settings" FOR ALL
    USING (auth.email() = 'admin@gmail.com')
    WITH CHECK (auth.email() = 'admin@gmail.com');

CREATE POLICY "Enable read access for user based on user_name" ON "public"."notifications" FOR SELECT USING (auth.jwt()->>'full_name' = user_name);
CREATE POLICY "Enable insert for users based on user_name" ON "public"."notifications" FOR INSERT WITH CHECK (auth.jwt()->>'full_name' = user_name);
CREATE POLICY "Enable update for users based on user_name" ON "public"."notifications" FOR UPDATE USING (auth.jwt()->>'full_name' = user_name);
CREATE POLICY "Enable delete for users based on user_name" ON "public"."notifications" FOR DELETE USING (auth.jwt()->>'full_name' = user_name);

-- Grant usage on schema public to postgres and anon roles
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;

-- Grant all privileges on all tables in schema public to the postgres role
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;

-- Grant necessary privileges to the anon role (for read-only access)
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;
GRANT INSERT ON public.notifications TO anon; -- Allow users to create their own notifications
GRANT UPDATE ON public.notifications TO anon;
GRANT DELETE ON public.notifications TO anon;


-- Grant necessary privileges to the service_role (for server-side operations like functions)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO service_role;
