
-- Drop existing objects in reverse dependency order to avoid errors
DROP POLICY IF EXISTS "Enable all access for admins" ON public.notices;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.notices;
DROP TABLE IF EXISTS public.notices;

DROP POLICY IF EXISTS "Enable all access for admins" ON public.settings;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.settings;
DROP TABLE IF EXISTS public.settings;

DROP POLICY IF EXISTS "Enable all access for admins" ON public.admins;
DROP TABLE IF EXISTS public.admins;

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.notifications;
DROP POLICY IF EXISTS "Users can update their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can view their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can delete their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Admins can manage all notifications" ON public.notifications;
DROP TABLE IF EXISTS public.notifications;

DROP POLICY IF EXISTS "Enable all for admin" ON storage.objects;
DROP POLICY IF EXISTS "Enable read for all" ON storage.objects;
DROP POLICY IF EXISTS "Allow user to upload own avatar" ON storage.objects;
DROP POLICY IF EXISTS "Allow user to update own avatar" ON storage.objects;

-- Drop trigger and function if they exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

DROP FUNCTION IF EXISTS public.is_admin(user_id uuid);
DROP FUNCTION IF EXISTS public.get_user_role(user_id uuid);


-- Create Admins Table
CREATE TABLE public.admins (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Create Players Table
CREATE TABLE public.players (
    id uuid not null primary key references auth.users (id) on delete cascade,
    name text not null,
    email text unique,
    skill_level text default 'Beginner'::text,
    matches_played integer default 0,
    win_rate text default '0%',
    highest_break integer default 0,
    avatar text,
    initials text,
    wins integer default 0,
    losses integer default 0,
    average_break integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

-- Create Tournaments Table
CREATE TABLE public.tournaments (
    id bigint generated by default as identity primary key,
    name text not null,
    format text,
    players integer,
    status text,
    rules text[],
    image text,
    pendingPlayers text[],
    registeredPlayers text[],
    location text,
    winner text,
    bracket jsonb
);
ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;

-- Create Matches Table
CREATE TABLE public.matches (
    id bigint generated by default as identity primary key,
    winner text,
    loser text,
    score text,
    date timestamp with time zone not null,
    media text[],
    comments jsonb,
    pending_score jsonb,
    tournament_id bigint references public.tournaments(id) on delete set null
);
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- Create Upcoming Matches Table
CREATE TABLE public.upcoming_matches (
    id bigint generated by default as identity primary key,
    player1 text not null,
    player2 text not null,
    date date not null,
    time text not null,
    tournament_id bigint references public.tournaments(id) on delete set null
);
ALTER TABLE public.upcoming_matches ENABLE ROW LEVEL SECURITY;

-- Create Live Matches Table
CREATE TABLE public.live_matches (
    id bigint generated by default as identity primary key,
    tournament_id bigint,
    tournament_name text,
    player1 text,
    player2 text,
    score1 integer,
    score2 integer
);
ALTER TABLE public.live_matches ENABLE ROW LEVEL SECURITY;

-- Create Notifications Table
CREATE TABLE public.notifications (
  id bigint generated by default as identity primary key,
  user_name text not null,
  title text not null,
  description text not null,
  read boolean default false,
  date timestamp with time zone not null,
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Create Notices Table
CREATE TABLE public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  date timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

-- Create Settings Table
CREATE TABLE public.settings (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;


-- Helper Functions
create or replace function public.is_admin(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists(select 1 from admins where admins.user_id = is_admin.user_id);
$$;

create or replace function public.get_user_role(user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if is_admin(user_id) then
    return 'admin';
  else
    return 'user';
  end if;
end;
$$;


-- Player Creation Trigger Function
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.players (id, name, email, initials, avatar)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    (new.raw_user_meta_data->>'full_name')::text
      |> split_part(1, ' ')
      |> substr(1, 1)
      || (new.raw_user_meta_data->>'full_name')::text
      |> split_part(2, ' ')
      |> substr(1, 1),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;

-- Player Creation Trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Storage Bucket for Avatars
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/gif'])
on conflict (id) do nothing;


-- RLS Policies
-- Admins Table
CREATE POLICY "Enable all access for admins" ON public.admins FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- Players Table
CREATE POLICY "Enable read access for all users" ON public.players FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile" ON public.players FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Enable full access for admins" ON public.players FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- Matches Table
CREATE POLICY "Enable read access for all users" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create matches" ON public.matches FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can manage all matches" ON public.matches FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Users can update their own matches" ON public.matches FOR UPDATE USING (
  auth.uid() IN (SELECT id FROM public.players WHERE name = winner) OR
  auth.uid() IN (SELECT id FROM public.players WHERE name = loser)
) WITH CHECK (
  auth.uid() IN (SELECT id FROM public.players WHERE name = winner) OR
  auth.uid() IN (SELECT id FROM public.players WHERE name = loser)
);


-- Upcoming Matches Table
CREATE POLICY "Enable read access for all users" ON public.upcoming_matches FOR SELECT USING (true);
CREATE POLICY "Enable all access for admins" ON public.upcoming_matches FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- Live Matches Table
CREATE POLICY "Enable read access for all users" ON public.live_matches FOR SELECT USING (true);
CREATE POLICY "Enable all access for admins" ON public.live_matches FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- Tournaments Table
CREATE POLICY "Enable read access for all users" ON public.tournaments FOR SELECT USING (true);
CREATE POLICY "Enable all access for admins" ON public.tournaments FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Authenticated users can update tournaments they are in" ON public.tournaments FOR UPDATE TO authenticated USING (
    (registeredPlayers @> ARRAY[auth.jwt()->>'email']) OR (pendingPlayers @> ARRAY[auth.jwt()->>'email'])
) WITH CHECK (
    (registeredPlayers @> ARRAY[auth.jwt()->>'email']) OR (pendingPlayers @> ARRAY[auth.jwt()->>'email'])
);

-- Notifications Table
CREATE POLICY "Users can manage their own notifications" ON public.notifications FOR ALL USING (
  auth.uid() IN (SELECT id FROM public.players WHERE name = user_name)
) WITH CHECK (
  auth.uid() IN (SELECT id FROM public.players WHERE name = user_name)
);
CREATE POLICY "Admins can manage all notifications" ON public.notifications FOR ALL USING (public.is_admin(auth.uid()));
CREATE POLICY "Enable insert for authenticated users" ON public.notifications FOR INSERT TO authenticated WITH CHECK (true);


-- Notices Table
CREATE POLICY "Enable read access for all users" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Enable all access for admins" ON public.notices FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- Settings Table
CREATE POLICY "Enable read access for all users" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Enable all access for admins" ON public.settings FOR ALL USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));


-- Storage RLS Policies
CREATE POLICY "Enable read access for all users" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
CREATE POLICY "Allow user to upload own avatar" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'avatars' AND auth.uid() = (storage.foldername(name))[1]::uuid);
CREATE POLICY "Allow user to update own avatar" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'avatars' AND auth.uid() = (storage.foldername(name))[1]::uuid);

-- Grant usage on schema to roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;

-- Grant permissions on tables to roles
GRANT ALL ON TABLE public.admins TO postgres, service_role;
GRANT SELECT ON TABLE public.admins TO anon, authenticated;

GRANT ALL ON TABLE public.live_matches TO postgres, service_role;
GRANT SELECT ON TABLE public.live_matches TO anon, authenticated;

GRANT ALL ON TABLE public.matches TO postgres, service_role;
GRANT SELECT ON TABLE public.matches TO anon, authenticated;

GRANT ALL ON TABLE public.notices TO postgres, service_role;
GRANT SELECT ON TABLE public.notices TO anon, authenticated;

GRANT ALL ON TABLE public.notifications TO postgres, service_role;
GRANT SELECT ON TABLE public.notifications TO anon, authenticated;

GRANT ALL ON TABLE public.players TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.players TO anon, authenticated;

GRANT ALL ON TABLE public.settings TO postgres, service_role;
GRANT SELECT ON TABLE public.settings TO anon, authenticated;

GRANT ALL ON TABLE public.tournaments TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.tournaments TO anon, authenticated;

GRANT ALL ON TABLE public.upcoming_matches TO postgres, service_role;
GRANT SELECT ON TABLE public.upcoming_matches TO anon, authenticated;

-- Grant execute on functions to roles
GRANT EXECUTE ON FUNCTION public.get_user_role(uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO anon, authenticated, service_role;
