
-- Drop dependent objects before dropping the function
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Drop existing policies before tables to avoid dependency issues
DROP POLICY IF EXISTS "Enable read access for all users" ON public.players;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.players;
DROP POLICY IF EXISTS "Enable update for users based on email" ON public.players;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.matches;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.matches;
DROP POLICY IF EXISTS "Enable update for users based on email" ON public.matches;
DROP POLICY IF EXISTS "Enable delete for users based on email" ON public.matches;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.tournaments;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.notices;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.live_matches;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.upcoming_matches;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.notifications;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.notifications;
DROP POLICY IF EXISTS "Enable update for users based on id" ON public.notifications;
DROP POLICY IF EXISTS "Enable delete for users based on name" ON public.notifications;
DROP POLICY IF EXISTS "Enable access for admins" ON public.settings;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.settings;
DROP POLICY IF EXISTS "Allow admin to manage avatars" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload avatars" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to view avatars" ON storage.objects;

-- Drop tables in reverse order of creation
DROP TABLE IF EXISTS public.live_matches;
DROP TABLE IF EXISTS public.upcoming_matches;
DROP TABLE IF EXISTS public.notifications;
DROP TABLE IF EXISTS public.matches;
DROP TABLE IF EXISTS public.tournaments;
DROP TABLE IF EXISTS public.notices;
DROP TABLE IF EXISTS public.players;
DROP TABLE IF EXISTS public.settings;
DROP TABLE IF EXISTS public.admins;

-- Drop functions and types
DROP FUNCTION IF EXISTS public.is_admin(user_id uuid);

-- Recreate tables
CREATE TABLE public.players (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    email text,
    skill_level text DEFAULT 'Beginner'::text NOT NULL,
    matches_played integer DEFAULT 0 NOT NULL,
    win_rate text DEFAULT '0%'::text NOT NULL,
    highest_break integer DEFAULT 0 NOT NULL,
    avatar text,
    initials text,
    wins integer,
    losses integer,
    average_break integer
);
ALTER TABLE public.players ADD CONSTRAINT players_pkey PRIMARY KEY (id);
ALTER TABLE public.players ADD CONSTRAINT players_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE TABLE public.matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    winner text,
    loser text,
    score text,
    date date,
    media text[],
    "comments" jsonb,
    pending_score jsonb,
    tournament_id bigint
);
ALTER TABLE public.matches ADD CONSTRAINT matches_pkey PRIMARY KEY (id);

CREATE TABLE public.tournaments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text,
    format text,
    players integer,
    status text,
    rules text[],
    image text,
    pendingPlayers text[],
    registeredPlayers text[],
    location text,
    winner text,
    bracket jsonb
);
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_pkey PRIMARY KEY (id);
ALTER TABLE public.matches ADD CONSTRAINT matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE SET NULL;


CREATE TABLE public.notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text,
    content text,
    date timestamp with time zone
);
ALTER TABLE public.notices ADD CONSTRAINT notices_pkey PRIMARY KEY (id);

CREATE TABLE public.live_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    player1 text,
    player2 text,
    score1 integer,
    score2 integer,
    tournament_id bigint,
    tournament_name text
);
ALTER TABLE public.live_matches ADD CONSTRAINT live_matches_pkey PRIMARY KEY (id);

CREATE TABLE public.upcoming_matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    player1 text,
    player2 text,
    date date,
    "time" time without time zone,
    tournament_id bigint
);
ALTER TABLE public.upcoming_matches ADD CONSTRAINT upcoming_matches_pkey PRIMARY KEY (id);

CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_name text,
    title text,
    description text,
    read boolean DEFAULT false,
    date timestamp with time zone,
    link text
);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

CREATE TABLE public.settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    key text,
    value jsonb
);
ALTER TABLE public.settings ADD CONSTRAINT settings_pkey PRIMARY KEY (id);
ALTER TABLE public.settings ADD CONSTRAINT settings_key_key UNIQUE (key);

CREATE TABLE public.admins (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.admins ADD CONSTRAINT admins_pkey PRIMARY KEY (id);
ALTER TABLE public.admins ADD CONSTRAINT admins_user_id_key UNIQUE (user_id);
ALTER TABLE public.admins ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- BUCKET for avatars
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('avatars', 'avatars', true, 5242880, ARRAY['image/png', 'image/jpeg', 'image/gif'])
ON CONFLICT (id) DO NOTHING;

-- FUNCTIONS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.players (id, email, name, avatar, initials)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'full_name',
    NEW.raw_user_meta_data ->> 'avatar_url',
    (SELECT string_agg(SUBSTRING(name, 1, 1), '') FROM unnest(string_to_array(NEW.raw_user_meta_data ->> 'full_name', ' ')) name)
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM public.admins WHERE public.admins.user_id = is_admin.user_id);
END;
$$;


-- TRIGGERS
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- POLICIES for players
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.players FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.players FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on email" ON public.players FOR UPDATE USING ((SELECT auth.email()) = email OR is_admin(auth.uid())) WITH CHECK ((SELECT auth.email()) = email OR is_admin(auth.uid()));

-- POLICIES for matches
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.matches FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on email" ON public.matches FOR UPDATE TO authenticated USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));
CREATE POLICY "Enable delete for users based on email" ON public.matches FOR DELETE TO authenticated USING (is_admin(auth.uid()));

-- POLICIES for tournaments
ALTER TABLE public.tournaments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.tournaments FOR SELECT USING (true);

-- POLICIES for notices, live_matches, upcoming_matches
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.notices FOR SELECT USING (true);

ALTER TABLE public.live_matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.live_matches FOR SELECT USING (true);

ALTER TABLE public.upcoming_matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.upcoming_matches FOR SELECT USING (true);

-- POLICIES for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.notifications FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.notifications FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on id" ON public.notifications FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for users based on name" ON public.notifications FOR DELETE TO authenticated USING ((SELECT auth.uid()::text) = user_name OR is_admin(auth.uid()));

-- POLICIES for settings
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Enable access for admins" ON public.settings FOR ALL USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

-- POLICIES for storage
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin to manage avatars"
ON storage.objects FOR ALL
USING (bucket_id = 'avatars' AND is_admin(auth.uid()));

CREATE POLICY "Allow authenticated users to upload avatars"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "Allow authenticated users to view avatars"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'avatars');
